dependencies:
  - python>=3.10
  - pip
  - setuptools<82
  - pytorch
  - scipy
  - numpy
  - pandas
  - scikit-learn
  - scikit-image
  - tqdm
  - matplotlib-base
  - seaborn
  - jupyterlab
  - pip:
      - scanpy
      - squidpy
      - ray[train,tune]